### ISSUE TITLE
Make Purchase With Mada

### ISSUE THREAD

**Issue by OmarAyoub07** [developermypos/myPOS-SDK-dotNET#3]
Hi, I need some help
I followed the steps and everything alright but i faced two problems:
1- In My (PAX A920), the transactions is done using (Mada application) it's popular in Saudi Arabia,
 When I try to make purchase requeste nothing happen.

 2- There is no `Currencies.SAR` to match it with my transactions.

**Comment by developermypos** [comment]
myPOS has license to operate only in EU, EEA and UK. There is no support for SAR yet.
